CREATE TABLE [dbo].[RefGender]
(
    [Id] TINYINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL UNIQUE,
    [Description] NVARCHAR(200) NULL
)
GO

CREATE TABLE [dbo].[RefContactType]
(
    [Id] TINYINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL UNIQUE,
    [Description] NVARCHAR(200) NULL
)
GO
