namespace Neoron.API.Models
{
    /// <summary>
    /// Represents the type of a Discord message.
    /// </summary>
    public enum MessageType : byte
    {
        /// <summary>
        /// A regular message sent by a user.
        /// </summary>
        Regular = 0,

        /// <summary>
        /// A system message generated by Discord.
        /// </summary>
        System = 1,
    }
}
